server:
  port: 8182

spring:
  application:
    name: user-center-service
  datasource:
    url: jdbc:mysql://localhost:3306/fengtao?useUnicode=true&characterEncoding=utf-8
    username: root
    password: gqlofe
    driver-class-name: com.mysql.jdbc.Driver
druid:
  initial-size: 2
  maxActive: 20
  min-idle: 0
  max-wait: 60000
  validation-query: SELECT 1
  test-on-borrow: false
  test-while=idle: true
  pool-prepared-statements: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

